import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Libre_Franklin } from 'next/font/google'
import { ScreenSize } from "@/components/screen";



const libre = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre.className+"bg-white"}>
        <ScreenSize />
        {children}</body>
    </html>
  );
}
